# services:
#   main:
#     build: .
#     ports:
#       - "8080:8080"
#     environment:
#       - OPENAI_API_KEY=${OPENAI_API_KEY}
#       - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
#       - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
#       - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
#     volumes:
#       - .:/app

#   jupyter:
#     build: .
#     ports:
#       - "8888:8888"
#     environment:
#       - OPENAI_API_KEY=${OPENAI_API_KEY}
#       - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
#       - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
#       - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
#     volumes:
#       - .:/app
#     command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root

services:
  main:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
    volumes:
      - .:/app

  jupyter:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
    depends_on:
      - main
    ports:
      - "8888:8888"
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root

  agent:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
    depends_on:
      - main
    ports:
      - "8000:8000"
    command: python in_class_examples/agent/server.py --ip=0.0.0.0 --port=8000

  chat:
    build: .
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGCHAIN_API_KEY=${LANGCHAIN_API_KEY}
      - LANGCHAIN_TRACING_V2=${LANGCHAIN_TRACING_V2}
      - LANGCHAIN_PROJECT=${LANGCHAIN_PROJECT}
    depends_on:
      - main
    ports:
      - "8002:8002"
    command: python in_class_examples/chat_with_persistence/server.py --ip=0.0.0.0 --port=8002
